from . import routes_cv
from . import routes_candidates
from . import routes_jobs
from . import routes_matches
from . import routes_applications
from . import routes_review
from . import routes_logs
from . import routes_settings
from . import routes_notifications
from . import routes_mcp
